// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegexMaster.DB;

#nullable disable

namespace RegexMaster.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20240622210244_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RegexMaster.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SignUpDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            Password = "password1",
                            SignUpDate = new DateTime(2024, 6, 22, 23, 2, 42, 876, DateTimeKind.Local).AddTicks(3779)
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            Password = "password2",
                            SignUpDate = new DateTime(2024, 6, 22, 23, 2, 42, 876, DateTimeKind.Local).AddTicks(3832)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
